FROM node:18-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the app's source code
COPY . .

# Expose the React development port
EXPOSE 3000

# Command to start the React development server
CMD ["npm", "start"]